development:
  adapter: postgresql
  database: hundred_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: hundred_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hundred_production
  pool: 5
  timeout: 5000
